version: '3'
services:
  strapi:
    container_name: portfolio.online
    build: .
    image: portfolio.online:latest
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./:/opt/app
    ports:
      - '1338:400'
